NoteApplication/ViewModels/NoteViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NoteApplication.ViewModels
{
    public class NoteViewModel
    {
        [ScaffoldColumn(false)]
        [Key]
        public int Id { get; set; }

        [DisplayName("Title")]
        [Required(ErrorMessage = "The note title is required field")]
        [StringLength(20)]
        public string Title { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "The note description is required field")]
        [StringLength(100)]
        public string Description { get; set; }
    }
}

NoteApplication/Controllers/NotesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http.Description;
using AutoMapper;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Mvc;
using NoteApplication.Repositories;
using NoteApplication.ViewModels;

namespace NoteApplication.Controllers
{
    public class NotesController : Controller
    {  
        private IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public NotesController(IMapper mapper, IUnitOfWork unitOfWork )
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        [Route("notes/")]
        [ResponseType(typeof(NoteViewModel))]
        public async Task<IActionResult> Index()
        {
            var notes = await _unitOfWork.NoteRepository.SelectAll();
            var notesViewModel = _mapper.Map<List<NoteViewModel>>(notes);
            return View(notesViewModel);
        }

        [Route("notes/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            var note = await _unitOfWork.NoteRepository.SelectByID(id.Value);
            var noteViewModel = _mapper.Map<NoteViewModel>(note);
            return View(noteViewModel);
        }

        [Route("notes/create")]
        public IActionResult Create()
        {
            var model = new NoteViewModel();
            return View(model);
        }

        [Route("notes/create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateConfirmed(NoteViewModel noteViewModel)
        {
            var note = new Note();
            var newNote = _mapper.Map(noteViewModel, note);
            await _unitOfWork.NoteRepository.Insert(newNote);
            await _unitOfWork.SaveAsync();       
            return RedirectToAction("Index");
        }

        [Route("notes/edit/{id}")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var note = await _unitOfWork.NoteRepository.SelectByID(id.Value);
            var noteViewModel = new NoteViewModel();
            var editedNote = _mapper.Map(note, noteViewModel);
            return View(editedNote);
        }

        [Route("notes/edit/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditConfirmed(NoteViewModel noteViewModel)
        {
            var note = new Note();
            var newNote = _mapper.Map(noteViewModel, note);
            _unitOfWork.NoteRepository.Update(newNote);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }

        [Route("notes/delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var note = await _unitOfWork.NoteRepository.SelectByID(id.Value);
            var noteViewModel = new NoteViewModel();
            var deletedNote = _mapper.Map(note, noteViewModel);
            return View(deletedNote);
        }

        [HttpPost]
        [Route("notes/delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(NoteViewModel noteViewModel, int? id)
        {
            var note = await _unitOfWork.NoteRepository.SelectByID(id.Value);
            var deleteNote = _mapper.Map(noteViewModel, note);
            _unitOfWork.NoteRepository.Delete(deleteNote);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }
    }
}

NoteApplication/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NoteApplication.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

NoteApplication/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NoteApplication.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

NoteApplication/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NoteApplication.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NoteApplication/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NoteApplication.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

NoteApplication/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Lorem ipsum dolor sit amet consectetuer</p>

NoteApplication/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NoteApplication/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<h2>@ViewData["Title"]</h2>

<div>
    <p>
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
    </p>
</div>

NoteApplication/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Note Application</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
    <div class='container'>
        <h1>Note Application</h1>
        <div class='navbar navbar-inverse'>
            <div class='navbar-inner nav-collapse' style="height: auto;">
                <ul class="nav">
                    <li><a href="/index">Home</a></li>
                    <li><a href="/notes">Notes</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>

            </div>
        </div>
        <div id='content' class='row-fluid'>
            <!---<div class='span2 sidebar'>
                <h3>Left Sidebar</h3>
                <ul class="nav nav-tabs nav-stacked">
                    <li><a href='/notes'>Another Link 1</a></li>
                    <li><a href='#'>Another Link 2</a></li>
                    <li><a href='#'>Another Link 3</a></li>
                </ul>
            </div>-->
            <div class='span8 main'>
                @RenderBody()
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; 2017 - Note Application</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <style>
        h1 {
            text-align: center;
        }

        body {
            font-family: Constantia, 'Times New Roman', sans-serif;
            background-color: aliceblue;
            font-size: 16px;
        }
    </style>
    @RenderSection("Scripts", required: false)
</body>

</html>

NoteApplication/Views/Notes/Create.cshtml
@model NoteApplication.ViewModels.NoteViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/_Layout.cshtml";
}

<div>
    <hr />
    @Html.AntiForgeryToken()

    @using (Html.BeginForm("Create", "Notes", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Title" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Description" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NoteApplication/Views/Notes/Delete.cshtml
@model NoteApplication.ViewModels.NoteViewModel
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            @Html.AntiForgeryToken()
            @using (Html.BeginForm("Delete", "Notes", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <p> Are you sure you want to delete note @Html.DisplayFor(x => Model.Title) ?</p>
                    @Html.HiddenFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <input type="submit" value="Delete" class="btn btn-danger" />
            }
        </div>
    </div>
</div>

<style>
    .row {
        margin-top: 40px;
        padding: 0 10px;
    }

    .clickable {
        cursor: pointer;
    }

    .panel-heading div {
        margin-top: -18px;
        font-size: 15px;
    }

        .panel-heading div span {
            margin-left: 5px;
        }

    .panel-body {
        display: none;
    }
</style>

NoteApplication/Views/Notes/Details.cshtml
@model NoteApplication.ViewModels.NoteViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/_Layout.cshtml";
}

@Html.DropDownListFor(model => model.Id, new SelectList(new[]{"Exemplo1",
"Exemplo2", "Exemplo3"}))
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>

<div>
    <a class="btn btn-warning" href="../Notes/Edit/@Model.Id" role="button">Edit</a>
</div>

NoteApplication/Views/Notes/Edit.cshtml
@model NoteApplication.ViewModels.NoteViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/_Layout.cshtml";
}
<div>
    @Html.AntiForgeryToken()

    @using (Html.BeginForm("Edit", "Notes", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-warning" />
            </div>
        </div>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NoteApplication/Views/Notes/Index.cshtml
@model IEnumerable<NoteApplication.ViewModels.NoteViewModel>
@{
    ViewData["Title"] = "Notes";
    Layout = "~/Pages/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">
                        <div class="row">
                            <div class="col-xs-6">
                                <h5><span class="glyphicon glyphicon-pencil"></span> Notes</h5>
                            </div>
                            <div class="col-xs-6">
                                <a class="btn btn-success btn-sm btn-block" href="~/notes/create" role="button">
                                    <i class="fa fa-plus" aria-hidden="true"></i>
                                    Create note
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <table class="table table-hover" id="dev-table">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Id)</th>
                            <th>@Html.DisplayNameFor(model => model.Title)</th>
                            <th>@Html.DisplayNameFor(model => model.Description)</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    <a class="btn btn-warning" href="~/notes/edit/@item.Id" role="button">
                                        <i class="fa fa-cog"></i>
                                        Edit
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-danger" href="~/notes/delete/@item.Id" role="button">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                        Delete
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-info" href="~/notes/@item.Id" role="button">
                                        <i class="fa fa-info-circle" aria-hidden="true"></i>
                                        Details
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--  <a class="btn btn-success" href="~/notes/create" role="button">
               <i class="fa fa-plus" aria-hidden="true"></i>
               Create note
          </a>
    -->
</div>

<style>
    .container {
        font-family: Constantia, 'Times New Roman', sans-serif;
        background-color: aliceblue;
        font-size: 16px;
    }

    .row {
        margin-top: 10px;
        padding: 0 10px;
    }

    .clickable {
        cursor: pointer;
    }

    .panel-body {
        display: none;
    }

    table {
        background-color: aliceblue;
    }
</style>

<script>
    (function () {
        'use strict';
        var $ = jQuery;
        $.fn.extend({
            filterTable: function () {
                return this.each(function () {
                    $(this).on('keyup', function (e) {
                        $('.filterTable_no_results').remove();
                        var $this = $(this), search = $this.val().toLowerCase(), target = $this.attr('data-filters'), $target = $(target), $rows = $target.find('tbody tr');
                        if (search == '') {
                            $rows.show();
                        } else {
                            $rows.each(function () {
                                var $this = $(this);
                                $this.text().toLowerCase().indexOf(search) === -1 ? $this.hide() : $this.show();
                            })
                            if ($target.find('tbody tr:visible').size() === 0) {
                                var col_count = $target.find('tr').first().find('td').size();
                                var no_results = $('<tr class="filterTable_no_results"><td colspan="' + col_count + '">No results found</td></tr>')
                                $target.find('tbody').append(no_results);
                            }
                        }
                    });
                });
            }
        });
        $('[data-action="filter"]').filterTable();
    })(jQuery);

    $(function () {
        // attach table filter plugin to inputs
        $('[data-action="filter"]').filterTable();

        $('.container').on('click', '.panel-heading span.filter', function (e) {
            var $this = $(this),
                $panel = $this.parents('.panel');

            $panel.find('.panel-body').slideToggle();
            if ($this.css('display') != 'none') {
                $panel.find('.panel-body input').focus();
            }
        });
        $('[data-toggle="tooltip"]').tooltip();
    })</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}